// Creating Variables 
let btn1 = document.getElementsByClassName('btn btn-primary');
let btn2 = document.getElementsByClassName('btn btn-danger');
let btn3 = document.getElementsByClassName('btn btn-success');
let btn4 = document.getElementsByClassName('btn btn-dark');
let outcome = document.getElementById('outcome');

// Creating Outcomes
let outcomes_strike_one = [
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter hit a SINGLE',
    'Batter hit a DOUBLE',
    'Batter hit a TRIPLE',
    'Batter hit a HOMERUN',
    'Error in field',
    'Error in field',
    'Error in field',
]

let outcomes_strike_two = [
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter did not swing',
    'Batter swung and miss',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter hit a SINGLE',
    'Batter hit a DOUBLE',
    'Batter hit a TRIPLE',
    'Batter hit a HOMERUN',
    'Error in field',
    'Error in field',
    'Error in field',
]

let outcomes_strike_three = [
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter struck out looking',
    'Batter struck out swinging',
    'Batter grounded out',
    'Batter flew out',
    'Batter hit a foul ball',
    'Batter hit a SINGLE',
    'Batter hit a DOUBLE',
    'Batter hit a TRIPLE',
    'Batter hit a HOMERUN',
    'Error in field',
    'Error in field',
    'Error in field',
]

// Creating Button Functionality
btn1[0].addEventListener('click', function onClick(){
    var strikeOne = outcomes_strike_one[Math.floor(Math.random() * outcomes_strike_one.length)]
    outcome.innerHTML = strikeOne; 
});

btn2[0].addEventListener('click', function onClick(){
    var strikeTwo = outcomes_strike_one[Math.floor(Math.random() * outcomes_strike_two.length)]
    outcome.innerHTML = strikeTwo; 
});

btn3[0].addEventListener('click', function onClick(){
    var strikeThree = outcomes_strike_one[Math.floor(Math.random() * outcomes_strike_three.length)]
    outcome.innerHTML = strikeThree; 
});

